# Generated by Django 5.0.3 on 2024-03-24 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('user_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('is_judge', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=128)),
                ('executor', models.CharField(max_length=128)),
                ('is_sended', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgvote.category')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=None)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgvote.performance')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgvote.tguser')),
            ],
        ),
    ]
