# Generated by Django 5.0.3 on 2024-03-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgvote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
