# Generated by Django 5.0.3 on 2025-04-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgvote', '0002_alter_score_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='is_olympic',
            field=models.BooleanField(default=False),
        ),
    ]
